### ISSUE TITLE
初始化发生错误

### ISSUE THREAD

**Issue by StephenFaust** [orchid-admin/axum-admin#2]
请输入超级管理员角色标识(默认:admin):
admin
请输入超级管理员用户名(默认:admin):
admin
请输入超级管理员登录密码(默认:admin123456):
admin123456
正在创建角色...
创建角色完成
正在创建登录账户...
thread 'main' panicked at app/cli/src/main.rs:27:32:
called `Result::unwrap()` on an `Err` value: QueryError("Error executing query: P2003 - Foreign key constraint failed on the field: `foreign key`")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tingfeng-key** [comment]
已修复
